// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-tasks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}
function toErr(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-tasks.ts
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's Eisenhower Matrix tasks. Optionally filter by status, quadrant, or category.",
  inputSchema: {
    status: z.enum(["open", "done"]).optional().describe("Filter by status."),
    quadrant: z.enum([
      "important-urgent",
      "important-not-urgent",
      "not-important-urgent",
      "not-important-not-urgent"
    ]).optional().describe("Filter by Eisenhower quadrant."),
    category: z.string().optional().describe("Filter by category name."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, quadrant, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("tasks").select("id,name,description,category,quadrant,due_date,due_time,status,created_at,updated_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (quadrant) q = q.eq("quadrant", quadrant);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a task for the signed-in user in a specific Eisenhower quadrant.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Task name."),
    description: z2.string().optional().describe("Optional longer description."),
    quadrant: z2.enum([
      "important-urgent",
      "important-not-urgent",
      "not-important-urgent",
      "not-important-not-urgent"
    ]).describe("Eisenhower quadrant."),
    category: z2.string().optional().describe("Category name (default 'General')."),
    due_date: z2.string().optional().describe("Due date YYYY-MM-DD."),
    due_time: z2.string().optional().describe("Due time HH:MM (24h).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async ({ name, description, quadrant, category, due_date, due_time }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("tasks").insert({
      user_id: ctx.getUserId(),
      name,
      description: description ?? null,
      quadrant,
      category: category ?? "General",
      due_date: due_date ?? null,
      due_time: due_time ?? null,
      status: "open"
    }).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Created task ${data.id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var complete_task_default = defineTool3({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as done (or reopen it).",
  inputSchema: {
    task_id: z3.string().uuid().describe("Task id."),
    done: z3.boolean().optional().describe("true to mark done (default), false to reopen.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true },
  handler: async ({ task_id, done }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const status = done === false ? "open" : "done";
    const { data, error } = await supabaseForUser(ctx).from("tasks").update({ status }).eq("id", task_id).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Task ${task_id} \u2192 ${status}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/delete-task.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var delete_task_default = defineTool4({
  name: "delete_task",
  title: "Delete task",
  description: "Permanently delete a task.",
  inputSchema: { task_id: z4.string().uuid().describe("Task id.") },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
  handler: async ({ task_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { error } = await supabaseForUser(ctx).from("tasks").delete().eq("id", task_id);
    if (error) return toErr(error.message);
    return { content: [{ type: "text", text: `Deleted task ${task_id}` }] };
  }
});

// src/lib/mcp/tools/list-notes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var list_notes_default = defineTool5({
  name: "list_notes",
  title: "List notes",
  description: "List the signed-in user's notes.",
  inputSchema: {
    category: z5.string().optional().describe("Filter by category."),
    limit: z5.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("notes").select("id,title,content,category,pinned,color,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { notes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-note.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^4.4.3";
var create_note_default = defineTool6({
  name: "create_note",
  title: "Create note",
  description: "Create a note for the signed-in user.",
  inputSchema: {
    title: z6.string().trim().min(1).describe("Note title."),
    content: z6.string().optional().describe("Markdown / plain text body."),
    category: z6.string().optional().describe("Category (default 'General')."),
    pinned: z6.boolean().optional().describe("Pin to the top.")
  },
  annotations: { readOnlyHint: false },
  handler: async ({ title, content, category, pinned }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("notes").insert({
      user_id: ctx.getUserId(),
      title,
      content: content ?? "",
      category: category ?? "General",
      pinned: pinned ?? false
    }).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Created note ${data.id}` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bvhwblwojecapnxivqnl";
var mcp_default = defineMcp({
  name: "weizen-mcp",
  title: "Weizen",
  version: "0.1.0",
  instructions: "Tools for the Weizen productivity app: read and manage the signed-in user's Eisenhower Matrix tasks and notes. Use list_tasks to see what's on their plate, create_task to add work into a specific quadrant, complete_task to mark items done, and list_notes / create_note for their notes.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_tasks_default,
    create_task_default,
    complete_task_default,
    delete_task_default,
    list_notes_default,
    create_note_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
