// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-tasks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.1";
import { z } from "npm:zod@^4.4.3";
var attachmentSchema = z.object({
  id: z.string().optional().describe("Stable id; auto-generated if omitted."),
  name: z.string().min(1).describe("Display label."),
  kind: z.enum(["file", "link"]).describe("'link' for URLs, 'file' for objects already in the task-attachments bucket."),
  path: z.string().min(1).describe("For links: full URL. For files: storage object path inside the task-attachments bucket."),
  size: z.number().int().nonnegative().optional(),
  contentType: z.string().optional(),
  addedAt: z.string().optional()
});
function normalizeAttachments(list) {
  const now = (/* @__PURE__ */ new Date()).toISOString();
  return list.map((a) => ({
    ...a,
    id: a.id ?? (globalThis.crypto?.randomUUID?.() ?? `${now}-${Math.random().toString(36).slice(2)}`),
    addedAt: a.addedAt ?? now
  }));
}
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}
function toErr(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/projectResolver.ts
async function resolveProjectPath(sb, userId, path, create = false) {
  if (!path?.trim()) return { projectId: null, created: [] };
  const parts = path.split("/").map((s) => s.trim()).filter(Boolean);
  if (parts.length === 0) return { projectId: null, created: [] };
  const { data, error } = await sb.from("project_templates").select("id,name,parent_id").eq("user_id", userId);
  if (error) throw new Error(error.message);
  const all = data ?? [];
  const created = [];
  let currentParent = null;
  let currentId = null;
  for (const part of parts) {
    const match = all.find(
      (p) => (p.parent_id ?? null) === currentParent && p.name.toLowerCase() === part.toLowerCase()
    );
    if (match) {
      currentId = match.id;
      currentParent = match.id;
      continue;
    }
    if (!create) return { projectId: null, created };
    const { data: inserted, error: insErr } = await sb.from("project_templates").insert({ user_id: userId, name: part, parent_id: currentParent }).select("id,name,parent_id").single();
    if (insErr) throw new Error(insErr.message);
    all.push(inserted);
    created.push(inserted.id);
    currentId = inserted.id;
    currentParent = inserted.id;
  }
  return { projectId: currentId, created };
}
async function descendantProjectIds(sb, userId, rootId) {
  const { data, error } = await sb.from("project_templates").select("id,parent_id").eq("user_id", userId);
  if (error) throw new Error(error.message);
  const rows = data ?? [];
  const childrenBy = /* @__PURE__ */ new Map();
  rows.forEach((r) => {
    const k = r.parent_id ?? null;
    if (!childrenBy.has(k)) childrenBy.set(k, []);
    childrenBy.get(k).push(r.id);
  });
  const out = [];
  const walk = (id) => {
    out.push(id);
    (childrenBy.get(id) ?? []).forEach(walk);
  };
  walk(rootId);
  return out;
}

// src/lib/mcp/tools/list-tasks.ts
var list_tasks_default = defineTool({
  name: "list_tasks",
  title: "List tasks",
  description: "List the signed-in user's Eisenhower Matrix tasks. Optionally filter by status, quadrant, or category.",
  inputSchema: {
    status: z2.enum(["open", "done"]).optional().describe("Filter by status."),
    quadrant: z2.enum([
      "important-urgent",
      "important-not-urgent",
      "not-important-urgent",
      "not-important-not-urgent"
    ]).optional().describe("Filter by Eisenhower quadrant."),
    project_id: z2.string().uuid().optional().describe("Filter to tasks under this project id (includes tasks on all descendant subprojects)."),
    project_path: z2.string().optional().describe("Alternative to project_id: '/'-separated project path."),
    category: z2.string().optional().describe("DEPRECATED. Filters tasks whose immediate project has this leaf name."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, quadrant, project_id, project_path, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("tasks").select(
      "id,name,description,quadrant,due_date,due_time,status,project_id,attachments,kanban_column,recurrence,recurrence_days,recurrence_time,is_recurring_instance,recurring_template_id,deadline_threshold_override,sort_order,created_at,updated_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (quadrant) q = q.eq("quadrant", quadrant);
    let filterProjectId = project_id ?? null;
    if (!filterProjectId && project_path) {
      const { projectId } = await resolveProjectPath(sb, ctx.getUserId(), project_path, false);
      filterProjectId = projectId;
    }
    if (filterProjectId) {
      const ids = await descendantProjectIds(sb, ctx.getUserId(), filterProjectId);
      q = q.in("project_id", ids);
    }
    const { data, error } = await q;
    if (error) return toErr(error.message);
    let rows = data ?? [];
    if (category) {
      const { data: projs } = await sb.from("project_templates").select("id,name").eq("user_id", ctx.getUserId());
      const nameById = new Map((projs ?? []).map((p) => [p.id, p.name.toLowerCase()]));
      const wanted = category.toLowerCase();
      rows = rows.filter((t) => t.project_id && nameById.get(t.project_id) === wanted);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { tasks: rows }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var create_task_default = defineTool2({
  name: "create_task",
  title: "Create task",
  description: "Create a task for the signed-in user in a specific Eisenhower quadrant. Supports description, project association, status, and attachments (links or already-uploaded files).",
  inputSchema: {
    name: z3.string().trim().min(1).describe("Task name."),
    description: z3.string().optional().describe("Optional longer description."),
    quadrant: z3.enum([
      "important-urgent",
      "important-not-urgent",
      "not-important-urgent",
      "not-important-not-urgent"
    ]).describe("Eisenhower quadrant."),
    category: z3.string().optional().describe(
      "DEPRECATED. Treated as a leaf subproject under `project_id` (or as a new top-level project if none). Prefer `project_path`."
    ),
    due_date: z3.string().optional().describe("Due date YYYY-MM-DD."),
    due_time: z3.string().optional().describe("Due time HH:MM (24h)."),
    project_id: z3.string().uuid().optional().describe("Associate the task with a specific project id (project_templates.id)."),
    project_path: z3.string().optional().describe(
      "Alternative to project_id: '/'-separated project path like 'Work/Q4/Launch'. Any missing intermediate projects are auto-created for the user."
    ),
    status: z3.enum(["open", "done"]).optional().describe("Initial status (default 'open'). Pass 'done' to create it already completed."),
    attachments: z3.array(attachmentSchema).optional().describe("Attachments to add. Use kind='link' with a URL, or kind='file' with an existing storage path in the task-attachments bucket.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async ({ name, description, quadrant, category, due_date, due_time, project_id, project_path, status, attachments }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let effectiveProjectId = project_id ?? null;
    if (!effectiveProjectId && project_path) {
      const { projectId } = await resolveProjectPath(sb, ctx.getUserId(), project_path, true);
      effectiveProjectId = projectId;
    }
    if (category && category !== "General") {
      const cur = effectiveProjectId;
      const { data: allProjects } = await sb.from("project_templates").select("id,name,parent_id").eq("user_id", ctx.getUserId());
      const existing = (allProjects ?? []).find(
        (p) => (p.parent_id ?? null) === cur && p.name.toLowerCase() === category.toLowerCase()
      );
      if (existing) {
        effectiveProjectId = existing.id;
      } else {
        const { data: created, error: cErr } = await sb.from("project_templates").insert({ user_id: ctx.getUserId(), name: category, parent_id: cur }).select("id").single();
        if (cErr) return toErr(cErr.message);
        effectiveProjectId = created.id;
      }
    }
    const { data, error } = await sb.from("tasks").insert({
      user_id: ctx.getUserId(),
      name,
      description: description ?? null,
      quadrant,
      due_date: due_date ?? null,
      due_time: due_time ?? null,
      status: status ?? "open",
      project_id: effectiveProjectId,
      attachments: attachments ? normalizeAttachments(attachments) : []
    }).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Created task ${data.id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/update-task.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var update_task_default = defineTool3({
  name: "update_task",
  title: "Update task",
  description: "Update fields on an existing task: name, description, quadrant (move between Eisenhower quadrants), category, due date/time (reschedule), status (mark done/reopen), project association, or attachments. Cannot change task ownership.",
  inputSchema: {
    task_id: z4.string().uuid().describe("Task id."),
    name: z4.string().trim().min(1).optional(),
    description: z4.string().nullable().optional(),
    quadrant: z4.enum([
      "important-urgent",
      "important-not-urgent",
      "not-important-urgent",
      "not-important-not-urgent"
    ]).optional().describe("Move task to a different Eisenhower quadrant."),
    category: z4.string().optional().describe("DEPRECATED. Replaces the task's project with a subproject having this name under the task's current parent (or a new top-level project). Prefer `project_id`/`project_path`."),
    due_date: z4.string().nullable().optional().describe("YYYY-MM-DD, or null to clear."),
    due_time: z4.string().nullable().optional().describe("HH:MM (24h), or null to clear."),
    status: z4.enum(["open", "done"]).optional().describe("Set to 'done' to complete, 'open' to reopen."),
    project_id: z4.string().uuid().nullable().optional().describe("Associate with a project, or null to detach."),
    project_path: z4.string().nullable().optional().describe("Alternative to project_id: '/'-separated project path; missing nodes are created."),
    attachments: z4.array(attachmentSchema).optional().describe("Attachments to add or replace. Use kind='link' with URL, or kind='file' with an existing storage path."),
    attachments_mode: z4.enum(["append", "replace"]).optional().describe("How to apply `attachments`: 'append' (default) adds to existing, 'replace' overwrites the full list.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true },
  handler: async ({ task_id, attachments, attachments_mode, project_path, category, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const patch = {};
    for (const [k, v] of Object.entries(fields)) {
      if (v !== void 0) patch[k] = v;
    }
    const sb = supabaseForUser(ctx);
    if (project_path !== void 0) {
      if (project_path === null || project_path === "") {
        patch.project_id = null;
      } else {
        const { projectId } = await resolveProjectPath(sb, ctx.getUserId(), project_path, true);
        patch.project_id = projectId;
      }
    } else if (category !== void 0) {
      const { data: current } = await sb.from("tasks").select("project_id").eq("id", task_id).single();
      const currentProjectId = current?.project_id ?? null;
      let parentId = null;
      if (currentProjectId) {
        const { data: cp } = await sb.from("project_templates").select("parent_id").eq("id", currentProjectId).single();
        parentId = cp?.parent_id ?? null;
      }
      if (!category || category === "General") {
        patch.project_id = parentId;
      } else {
        const { data: all } = await sb.from("project_templates").select("id,name,parent_id").eq("user_id", ctx.getUserId());
        const existing = (all ?? []).find((p) => (p.parent_id ?? null) === parentId && p.name.toLowerCase() === category.toLowerCase());
        if (existing) patch.project_id = existing.id;
        else {
          const { data: created, error: cErr } = await sb.from("project_templates").insert({ user_id: ctx.getUserId(), name: category, parent_id: parentId }).select("id").single();
          if (cErr) return toErr(cErr.message);
          patch.project_id = created.id;
        }
      }
    }
    if (attachments !== void 0) {
      const normalized = normalizeAttachments(attachments);
      if ((attachments_mode ?? "append") === "replace") {
        patch.attachments = normalized;
      } else {
        const { data: existing, error: readErr } = await sb.from("tasks").select("attachments").eq("id", task_id).single();
        if (readErr) return toErr(readErr.message);
        const current = Array.isArray(existing?.attachments) ? existing.attachments : [];
        patch.attachments = [...current, ...normalized];
      }
    }
    if (Object.keys(patch).length === 0)
      return toErr("No fields to update.");
    const { data, error } = await sb.from("tasks").update(patch).eq("id", task_id).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Updated task ${task_id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/complete-task.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var complete_task_default = defineTool4({
  name: "complete_task",
  title: "Complete task",
  description: "Mark a task as done (or reopen it).",
  inputSchema: {
    task_id: z5.string().uuid().describe("Task id."),
    done: z5.boolean().optional().describe("true to mark done (default), false to reopen.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true },
  handler: async ({ task_id, done }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const status = done === false ? "open" : "done";
    const { data, error } = await supabaseForUser(ctx).from("tasks").update({ status }).eq("id", task_id).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Task ${task_id} \u2192 ${status}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/delete-task.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^4.4.3";
var delete_task_default = defineTool5({
  name: "delete_task",
  title: "Delete task",
  description: "Permanently delete a task.",
  inputSchema: { task_id: z6.string().uuid().describe("Task id.") },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
  handler: async ({ task_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { error } = await supabaseForUser(ctx).from("tasks").delete().eq("id", task_id);
    if (error) return toErr(error.message);
    return { content: [{ type: "text", text: `Deleted task ${task_id}` }] };
  }
});

// src/lib/mcp/tools/list-notes.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^4.4.3";
var list_notes_default = defineTool6({
  name: "list_notes",
  title: "List notes",
  description: "List the signed-in user's notes.",
  inputSchema: {
    project_id: z7.string().uuid().optional().describe("Filter by project id (includes descendants)."),
    project_path: z7.string().optional().describe("Alternative to project_id: '/'-separated project path."),
    category: z7.string().optional().describe("DEPRECATED. Filters notes whose immediate project leaf name matches."),
    limit: z7.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, project_path, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let q = sb.from("notes").select("id,title,content,project_id,pinned,color,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    let filterProjectId = project_id ?? null;
    if (!filterProjectId && project_path) {
      const { projectId } = await resolveProjectPath(sb, ctx.getUserId(), project_path, false);
      filterProjectId = projectId;
    }
    if (filterProjectId) {
      const ids = await descendantProjectIds(sb, ctx.getUserId(), filterProjectId);
      q = q.in("project_id", ids);
    }
    const { data, error } = await q;
    if (error) return toErr(error.message);
    let rows = data ?? [];
    if (category) {
      const { data: projs } = await sb.from("project_templates").select("id,name").eq("user_id", ctx.getUserId());
      const nameById = new Map((projs ?? []).map((p) => [p.id, p.name.toLowerCase()]));
      const wanted = category.toLowerCase();
      rows = rows.filter((n) => n.project_id && nameById.get(n.project_id) === wanted);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { notes: rows }
    };
  }
});

// src/lib/mcp/tools/create-note.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^4.4.3";
var create_note_default = defineTool7({
  name: "create_note",
  title: "Create note",
  description: "Create a note for the signed-in user.",
  inputSchema: {
    title: z8.string().trim().min(1).describe("Note title."),
    content: z8.string().optional().describe("Markdown / plain text body."),
    category: z8.string().optional().describe("DEPRECATED. Treated as subproject-name under `project_path`/`project_id`."),
    project_id: z8.string().uuid().optional().describe("Attach to a specific project id."),
    project_path: z8.string().optional().describe("Alternative to project_id: '/'-separated project path; missing nodes are created."),
    pinned: z8.boolean().optional().describe("Pin to the top.")
  },
  annotations: { readOnlyHint: false },
  handler: async ({ title, content, category, project_id, project_path, pinned }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let effectiveProjectId = project_id ?? null;
    if (!effectiveProjectId && project_path) {
      const { projectId } = await resolveProjectPath(sb, ctx.getUserId(), project_path, true);
      effectiveProjectId = projectId;
    }
    if (category && category !== "General") {
      const cur = effectiveProjectId;
      const { data: all } = await sb.from("project_templates").select("id,name,parent_id").eq("user_id", ctx.getUserId());
      const existing = (all ?? []).find(
        (p) => (p.parent_id ?? null) === cur && p.name.toLowerCase() === category.toLowerCase()
      );
      if (existing) effectiveProjectId = existing.id;
      else {
        const { data: created, error: cErr } = await sb.from("project_templates").insert({ user_id: ctx.getUserId(), name: category, parent_id: cur }).select("id").single();
        if (cErr) return toErr(cErr.message);
        effectiveProjectId = created.id;
      }
    }
    const { data, error } = await sb.from("notes").insert({
      user_id: ctx.getUserId(),
      title,
      content: content ?? "",
      project_id: effectiveProjectId,
      pinned: pinned ?? false
    }).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Created note ${data.id}` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^4.4.3";
var list_projects_default = defineTool8({
  name: "list_projects",
  title: "List projects",
  description: "List the signed-in user's projects (project templates). Includes projects owned by the user.",
  inputSchema: {
    limit: z9.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("project_templates").select("id,name,description,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-project.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z10 } from "npm:zod@^4.4.3";
var create_project_default = defineTool9({
  name: "create_project",
  title: "Create project",
  description: "Create a new project for the signed-in user.",
  inputSchema: {
    name: z10.string().trim().min(1).describe("Project name."),
    description: z10.string().optional(),
    parent_id: z10.string().uuid().nullable().optional().describe("Parent project id \u2014 creates a subproject under it. Omit for a top-level project."),
    parent_path: z10.string().optional().describe("Alternative to parent_id: '/'-separated path to the parent project; missing nodes are auto-created.")
  },
  annotations: { readOnlyHint: false },
  handler: async ({ name, description, parent_id, parent_path }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    let effectiveParentId = parent_id ?? null;
    if (!effectiveParentId && parent_path) {
      const { projectId } = await resolveProjectPath(sb, ctx.getUserId(), parent_path, true);
      effectiveParentId = projectId;
    }
    const { data, error } = await sb.from("project_templates").insert({
      user_id: ctx.getUserId(),
      name,
      description: description ?? null,
      parent_id: effectiveParentId
    }).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Created project ${data.id}` }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-project-presets.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z11 } from "npm:zod@^4.4.3";
var list_project_presets_default = defineTool10({
  name: "list_project_template_presets",
  title: "List project template presets",
  description: "List the signed-in user's reusable project templates (presets).",
  inputSchema: {
    limit: z11.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("project_template_presets").select("id,name,description,tasks,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { presets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-project-preset.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z12 } from "npm:zod@^4.4.3";
var create_project_preset_default = defineTool11({
  name: "create_project_template_preset",
  title: "Create project template preset",
  description: "Create a reusable project template preset with a list of preset tasks.",
  inputSchema: {
    name: z12.string().trim().min(1),
    description: z12.string().optional(),
    tasks: z12.array(z12.record(z12.string(), z12.unknown())).optional().describe(
      "Array of preset task objects (name, description, dependencyType 'sync'|'async', dependsOn[], durationDays, etc.)."
    )
  },
  annotations: { readOnlyHint: false },
  handler: async ({ name, description, tasks }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("project_template_presets").insert({
      user_id: ctx.getUserId(),
      name,
      description: description ?? null,
      tasks: tasks ?? []
    }).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Created preset ${data.id}` }],
      structuredContent: { preset: data }
    };
  }
});

// src/lib/mcp/tools/list-kanban-boards.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z13 } from "npm:zod@^4.4.3";
var list_kanban_boards_default = defineTool12({
  name: "list_kanban_boards",
  title: "List kanban boards",
  description: "List the signed-in user's kanban boards and their columns.",
  inputSchema: {
    limit: z13.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data: boards, error } = await sb.from("kanban_boards").select("id,name,sort_order,created_at,updated_at").order("sort_order", { ascending: true }).limit(limit ?? 50);
    if (error) return toErr(error.message);
    const { data: columns, error: colErr } = await sb.from("kanban_columns").select("id,board_id,title,column_key,sort_order");
    if (colErr) return toErr(colErr.message);
    return {
      content: [{ type: "text", text: JSON.stringify({ boards, columns }) }],
      structuredContent: { boards: boards ?? [], columns: columns ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-kanban-board.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z14 } from "npm:zod@^4.4.3";
var create_kanban_board_default = defineTool13({
  name: "create_kanban_board",
  title: "Create kanban board",
  description: "Create a new kanban board with optional starter columns. Column keys are stable ids used when adding tasks.",
  inputSchema: {
    name: z14.string().trim().min(1),
    columns: z14.array(
      z14.object({
        title: z14.string().min(1),
        column_key: z14.string().min(1).describe("Stable key (e.g. 'todo').")
      })
    ).optional().describe("Optional initial columns. Defaults to To Do / Doing / Done.")
  },
  annotations: { readOnlyHint: false },
  handler: async ({ name, columns }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const { data: board, error } = await sb.from("kanban_boards").insert({ user_id: uid, name, sort_order: 0 }).select().single();
    if (error) return toErr(error.message);
    const cols = columns && columns.length > 0 ? columns : [
      { title: "To Do", column_key: "todo" },
      { title: "Doing", column_key: "doing" },
      { title: "Done", column_key: "done" }
    ];
    const { data: inserted, error: colErr } = await sb.from("kanban_columns").insert(
      cols.map((c, i) => ({
        user_id: uid,
        board_id: board.id,
        title: c.title,
        column_key: c.column_key,
        sort_order: i
      }))
    ).select();
    if (colErr) return toErr(colErr.message);
    return {
      content: [{ type: "text", text: `Created board ${board.id}` }],
      structuredContent: { board, columns: inserted ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-task-to-kanban.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z15 } from "npm:zod@^4.4.3";
var add_task_to_kanban_default = defineTool14({
  name: "add_task_to_kanban",
  title: "Add task to kanban",
  description: "Place an existing task on a kanban board in a specific column. Uses the column's stable key.",
  inputSchema: {
    board_id: z15.string().uuid(),
    task_id: z15.string().uuid(),
    column_key: z15.string().min(1).describe("Stable column key from list_kanban_boards."),
    sort_order: z15.number().int().optional()
  },
  annotations: { readOnlyHint: false },
  handler: async ({ board_id, task_id, column_key, sort_order }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("kanban_board_items").insert({
      user_id: ctx.getUserId(),
      board_id,
      task_id,
      column_key,
      sort_order: sort_order ?? 0
    }).select().single();
    if (error) return toErr(error.message);
    return {
      content: [{ type: "text", text: `Added task to board` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bvhwblwojecapnxivqnl";
var mcp_default = defineMcp({
  name: "weizen-mcp",
  title: "Weizen",
  version: "0.1.0",
  instructions: "Tools for the Weizen productivity app: read and manage the signed-in user's Eisenhower Matrix tasks and notes. Use list_tasks to see what's on their plate, create_task to add work into a specific quadrant, complete_task to mark items done, and list_notes / create_note for their notes.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_tasks_default,
    create_task_default,
    update_task_default,
    complete_task_default,
    delete_task_default,
    list_notes_default,
    create_note_default,
    list_projects_default,
    create_project_default,
    list_project_presets_default,
    create_project_preset_default,
    list_kanban_boards_default,
    create_kanban_board_default,
    add_task_to_kanban_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
